name: flutter_linter
description: Some flutter lints to avoid common flutter mistake
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer:
  analyzer_plugin:
  custom_lint_builder:
#  source_gen: ^1.2.2
  collection: ^1.18.0

dev_dependencies:
  lints: any
